export const site = {
  name: "Cockroach Watch India",
  shortName: "CWI",
  url: "https://cockroachwatchindia.online",
  email: "cockroachwatchindia@gmail.com",
  x: "https://x.com/CWatchIndia",
  instagram: "https://www.instagram.com/cockroachwatchindia/",
  youtube: "https://www.youtube.com/@CockroachWatchIndia",
  telegram: "https://t.me/cockroachwatchindia",
  reddit: "https://www.reddit.com/r/CockroachwatchIndia/",
  facebook: "https://www.facebook.com/profile.php?id=61590247497201",
  bluesky: "https://bsky.app/profile/cwatchindia.bsky.social",
  disclaimer:
    "Cockroach Watch India is an independent civic watch, satire, and commentary platform. Not affiliated with any political party or organization unless officially declared.",
  shortDisclaimer:
    "Independent civic watch, satire, and commentary platform. Not affiliated with any political party or organization unless officially declared.",
  description:
    "Cockroach Watch India is a founder-led civic watch, satire, and commentary platform documenting youth voice, public issues, viral civic moments, creator-led commentary, and the Cockroach wave across India.",
  keywords: [
    "Cockroach Watch India",
    "CWI",
    "Cockroach Janta Party",
    "CJP",
    "Cockroach wave",
    "Cockroach Watch",
    "Cockroach Janta Party watch",
    "CWI India",
    "youth voice India",
    "civic watch India",
    "Gen Z politics India",
    "political satire India",
    "Indian youth movement",
    "public issues India",
    "creator credit",
    "document verify amplify",
    "India is watching",
    "youth movement India",
    "youth voice",
    "Indian memes",
    "meme politics",
    "citizen journalism India",
    "RTI",
    "fact check",
    "viral India"
  ]
};
