export const site = {
  name: "Cockroach Watch India",
  shortName: "CWI",
  url: "https://www.cockroachwatchindia.online",
  email: "cockroachwatchindia@gmail.com",
  x: "https://x.com/CWatchIndia",
  instagram: "https://www.instagram.com/cockroachwatchindia/",
  youtube: "https://www.youtube.com/@CockroachWatchIndia",
  telegram: "https://t.me/cockroachwatchindia",
  reddit: "https://www.reddit.com/r/CockroachwatchIndia/",
  facebook: "https://www.facebook.com/profile.php?id=61590247497201",
  bluesky: "https://bsky.app/profile/cwatchindia.bsky.social",
  disclaimer:
    "Cockroach Watch India is an independent civic watch, satire, and commentary platform. Not affiliated with any political party or organization unless officially declared.",
  shortDisclaimer:
    "Independent civic watch, satire, and commentary platform. Not affiliated with any political party or organization unless officially declared.",
  description:
    "Cockroach Watch India, also known as CWI, is an independent civic watch, satire, and commentary platform documenting youth voice, public issues, creator credit, viral claims, and India's unanswered files.",
  keywords: [
    "Cockroach Watch India",
    "CWI",
    "CWI Live Newsroom",
    "CWI Archive",
    "CWI articles",
    "CWI civic watch",
    "CWI public issues",
    "CWI youth voice",
    "CWI digital rights",
    "CWI creator credit",
    "CWI public memory",
    "India Unanswered Files",
    "CWI India Unanswered Files",
    "Document Verify Amplify",
    "The youth are not silent India is watching",
    "Cockroach Janta Party",
    "CJP",
    "Cockroach wave",
    "Gen Z politics India",
    "political satire India",
    "civic satire India",
    "digital rights India",
    "viral claims India",
    "public issues India",
    "creator credit",
    "citizen journalism India",
    "RTI",
    "fact check India"
  ]
};
